/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */


const sidebars = {
  /*************  Ingles ********************/
  InglesA1: [
    {
      type:'autogenerated',
      dirName:'Ingles/A1',
    }
  ],
  InglesA2: [
    {
      type:'autogenerated',
      dirName:'Ingles/A2',
    }
  ],
  InglesB1: [
    {
      type:'autogenerated',
      dirName:'Ingles/B1',
    }
  ],
  InglesB2: [
    {
      type:'autogenerated',
      dirName:'Ingles/B2',
    }
  ],
  InglesC1: [
    {
      type:'autogenerated',
      dirName:'Ingles/C1',
    }
  ],
  InglesC2: [
    {
      type:'autogenerated',
      dirName:'Ingles/C2',
    }
  ],
  /**************** Programacion **********************/
  ProgramacionBasica:[
    {
      type:'autogenerated',
      dirName:'Programacion/Basico',
    }
  ],
  /**************** Herramientas de Automatizacion ****/
  Uipath:[
    {
      type:'autogenerated',
      dirName:'Automatizacion/Uipath',
    }
  ],
  RocketBot:[
    {
      type:'autogenerated',
      dirName:'Automatizacion/RocketBot',
    }
  ],
  AutomatizacionPython:[
    {
      type:'autogenerated',
      dirName:'Automatizacion/Python',
    }
  ],
  /**************** Inteligencia Artificial **********/
  IA_Grafos:[
    {
      type:'autogenerated',
      dirName:'IA/Grafos',
    }
  ],
  IA_Probabilidad:[
    {
      type:'autogenerated',
      dirName:'IA/Probabilidad',
    }
  ],
  IA_Logica:[
    {
      type:'autogenerated',
      dirName:'IA/Logica',
    }
  ],
  /***************** desarrollo web *****************/
  HTML:[
    {
      type:'autogenerated',
      dirName:'WEB/html',
    }
  ],
  CSS:[
    {
      type:'autogenerated',
      dirName:'WEB/css',
    }
  ],
  JS:[
    {
      type:'autogenerated',
      dirName:'WEB/javascript',
    }
  ],
};

module.exports = sidebars;
